### PR TITLE
Clean abs education data

### PR DESCRIPTION
**Pull request by aarathybabu97**

### CODE REVIEW

**Comment by aarathybabu97** [comment]
Issue #14

**Comment by njtierney** [comment]
Some ideas on implementing some of the school/work population/proporition information.

Similar to https://github.com/njtierney/conmat/blob/master/R/abs_age_lga.R

Instead the interface would be something like:

```r
abs_age_lga_education("Albury (C)")
abs_age_lga_work("Albury (C)")
```

Then this pulls out a similar table to https://github.com/njtierney/conmat/blob/master/R/abs_age_lga.R, but it contains information on

- lga
- age_group
- year
- proportion of population

With the "proportion of population" being regarding the proportion in education, and work, respectively.

Some other notes:

- This might not work for LGA here, it might only work for state.
- Can we get census data that contains general information on education/work rather than existing data we've been looking at (might need to use table builder)

**Comment by aarathybabu97** [comment]
LGA & State-wise data on education & work

```r

library(conmat)

data_abs_lga_education

#> # A tibble: 64,264 x 8
#>     year state lga          age population_educated total_population proportion
#>    <dbl> <chr> <chr>      <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 NSW   Albury (C)     0                   0              676      0    
#>  2  2016 NSW   Albury (C)     1                   0              664      0    
#>  3  2016 NSW   Albury (C)     2                   0              626      0    
#>  4  2016 NSW   Albury (C)     3                 250              706      0.354
#>  5  2016 NSW   Albury (C)     4                 431              609      0.708
#>  6  2016 NSW   Albury (C)     5                 533              608      0.877
#>  7  2016 NSW   Albury (C)     6                 595              631      0.943
#>  8  2016 NSW   Albury (C)     7                 608              644      0.944
#>  9  2016 NSW   Albury (C)     8                 575              609      0.944
#> 10  2016 NSW   Albury (C)     9                 630              680      0.926
#> # ... with 64,254 more rows, and 1 more variable: anomaly_flag <lgl>

data_abs_lga_work

#> # A tibble: 64,264 x 8
#>     year state lga            age employed_populati~ total_population proportion
#>    <dbl> <chr> <chr>        <dbl>              <dbl>            <dbl>      <dbl>
#>  1  2016 SA    Adelaide (C)     0                  0              132          0
#>  2  2016 SA    Adelaide (C)     1                  0              111          0
#>  3  2016 SA    Adelaide (C)     2                  0               85          0
#>  4  2016 SA    Adelaide (C)     3                  0               89          0
#>  5  2016 SA    Adelaide (C)     4                  0               86          0
#>  6  2016 SA    Adelaide (C)     5                  0               90          0
#>  7  2016 SA    Adelaide (C)     6                  0               72          0
#>  8  2016 SA    Adelaide (C)     7                  0               76          0
#>  9  2016 SA    Adelaide (C)     8                  0               72          0
#> 10  2016 SA    Adelaide (C)     9                  0               76          0
#> # ... with 64,254 more rows, and 1 more variable: anomaly_flag <lgl>

data_abs_state_education
#> # A tibble: 1,044 x 6
#>     year state   age population_educated total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 NSW       0                   0            87708      0    
#>  2  2016 NSW       1                   0            92876      0    
#>  3  2016 NSW       2                   0            93584      0    
#>  4  2016 NSW       3               45977            95179      0.483
#>  5  2016 NSW       4               66858            95791      0.698
#>  6  2016 NSW       5               84229            95216      0.885
#>  7  2016 NSW       6               91479            96479      0.948
#>  8  2016 NSW       7               90412            95142      0.950
#>  9  2016 NSW       8               91079            95833      0.950
#> 10  2016 NSW       9               90643            95516      0.949
#> # ... with 1,034 more rows

data_abs_state_work
#> # A tibble: 1,044 x 6
#>     year state   age employed_population total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 NSW       0                   0            87708          0
#>  2  2016 NSW       1                   0            92876          0
#>  3  2016 NSW       2                   0            93584          0
#>  4  2016 NSW       3                   0            95179          0
#>  5  2016 NSW       4                   0            95791          0
#>  6  2016 NSW       5                   0            95216          0
#>  7  2016 NSW       6                   0            96479          0
#>  8  2016 NSW       7                   0            95142          0
#>  9  2016 NSW       8                   0            95833          0
#> 10  2016 NSW       9                   0            95516          0
#> # ... with 1,034 more rows


```

**Comment by aarathybabu97** [comment]
Function to retrieve lga & state wise data on education and work

```r
get_data_abs_age_education(state = "VIC", age = 1:10)
#> # A tibble: 10 x 6
#>     year state   age population_educated total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 VIC       1                   0            74723      0    
#>  2  2016 VIC       2                   0            74475      0    
#>  3  2016 VIC       3               25354            76009      0.334
#>  4  2016 VIC       4               49763            75084      0.663
#>  5  2016 VIC       5               64489            73468      0.878
#>  6  2016 VIC       6               70717            74780      0.946
#>  7  2016 VIC       7               69543            73391      0.948
#>  8  2016 VIC       8               69673            73373      0.950
#>  9  2016 VIC       9               69894            73627      0.949
#> 10  2016 VIC      10               67584            71252      0.949

get_data_abs_age_education(lga = "Albury (C)", age = 10)
#> # A tibble: 1 x 8
#>    year state lga          age population_educated total_population proportion
#>   <dbl> <chr> <chr>      <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 NSW   Albury (C)    10                 615              654      0.940
#> # ... with 1 more variable: anomaly_flag <lgl>

get_data_abs_age_work(state = "NSW", age = 10:20)
#> # A tibble: 11 x 6
#>     year state   age employed_population total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 NSW      10                   0            92149      0    
#>  2  2016 NSW      11                   0            89078      0    
#>  3  2016 NSW      12                   0            87806      0    
#>  4  2016 NSW      13                   0            87596      0    
#>  5  2016 NSW      14                   0            86382      0    
#>  6  2016 NSW      15               15654            88159      0.178
#>  7  2016 NSW      16               23972            89421      0.268
#>  8  2016 NSW      17               28962            89131      0.325
#>  9  2016 NSW      18               41965            89447      0.469
#> 10  2016 NSW      19               51514            92265      0.558
#> 11  2016 NSW      20               55800            94364      0.591

get_data_abs_age_work(lga = "Barcoo (S)", age = 39)
#> # A tibble: 1 x 8
#>    year state lga          age employed_population total_population proportion
#>   <dbl> <chr> <chr>      <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 QLD   Barcoo (S)    39                   5                4       1.25
#> # ... with 1 more variable: anomaly_flag <lgl>

Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)


```

**Comment by njtierney** [comment]
``` r
library(conmat)
# allow multiple LGAs to work, as discussed, changing 
# `check_lga_name()` to by default accept multiple LGAs
# and then where it is currently used outside this function
# to enforce (one_lga = TRUE) (or something similar)
get_data_abs_age_work(lga = c("Albury (C)",
                              "Fairfield (C)"), 
                      age = 10)
#> Error in `check_lga_name()` at conmat/R/get_data_abs_age_work.R:21:4:
#> ! The LGA name provided matches multiple LGAs
#> ℹ Specify the exact LGA name. See `abs_lga_lookup` for a list of all LGAs
#> The lga name 'Albury (C)' matched multiple LGAs:
#> The lga name 'Fairfield (C)' matched multiple LGAs:
#> Albury (C)
#> Fairfield (C)


#  two edge cases
# What if we only call state? or only LGA? Can I get all ages back by default?
# set age = NULL, and detect if NULL, and return all ages
get_data_abs_age_education(state = "VIC")
#> Error in is_quosure(x): argument "x" is missing, with no default
get_data_abs_age_education(lga = "Albury (C)")
#> Error in is_quosure(x): argument "x" is missing, with no default
# what if we call both lga and state?
# it should error when both lga and state are given, instead it returns state
get_data_abs_age_education(lga = "Albury (C)", state = "QLD", age = 10)
#> # A tibble: 1 × 6
#>    year state   age population_educated total_population proportion
#>   <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 QLD      10               59180            62627      0.945
get_data_abs_age_education(lga = "Albury (C)", state = "VIC", age = 10)
#> # A tibble: 1 × 6
#>    year state   age population_educated total_population proportion
#>   <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 VIC      10               67584            71252      0.949
get_data_abs_age_education(lga = "Albury (C)", state = "NSW", age = 10)
#> # A tibble: 1 × 6
#>    year state   age population_educated total_population proportion
#>   <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 NSW      10               87573            92149      0.950
```

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.0 (2022-04-22)
#>  os       macOS Monterey 12.3.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_AU.UTF-8
#>  ctype    en_AU.UTF-8
#>  tz       Australia/Brisbane
#>  date     2022-05-26
#>  pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.2.0)
#>  cli           3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
#>  conmat      * 0.0.0.9004 2022-05-26 [1] local
#>  crayon        1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
#>  DBI           1.1.2      2021-12-20 [1] CRAN (R 4.2.0)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
#>  dplyr         1.0.9      2022-04-28 [1] CRAN (R 4.2.0)
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
#>  evaluate      0.15       2022-02-18 [1] CRAN (R 4.2.0)
#>  fansi         1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
#>  generics      0.1.2      2022-01-31 [1] CRAN (R 4.2.0)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.2.0)
#>  knitr         1.39       2022-04-26 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
#>  pillar        1.7.0      2022-02-01 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.2.0)
#>  rlang         1.0.2      2022-03-04 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.14       2022-04-25 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
#>  stringi       1.7.6      2021-11-29 [1] CRAN (R 4.2.0)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.2.0)
#>  tibble        3.1.7      2022-05-03 [1] CRAN (R 4.2.0)
#>  tidyselect    1.1.2      2022-02-21 [1] CRAN (R 4.2.0)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
#>  vctrs         0.4.1      2022-04-13 [1] CRAN (R 4.2.0)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.31       2022-05-10 [1] CRAN (R 4.2.0)
#>  yaml          2.3.5      2022-02-21 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by aarathybabu97** [comment]
```r
library(conmat)

# prints the data for all ages

get_data_abs_age_education(state="VIC")
#> # A tibble: 116 x 6
#>     year state   age population_educated total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 VIC       0                   0            70920      0    
#>  2  2016 VIC       1                   0            74723      0    
#>  3  2016 VIC       2                   0            74475      0    
#>  4  2016 VIC       3               25354            76009      0.334
#>  5  2016 VIC       4               49763            75084      0.663
#>  6  2016 VIC       5               64489            73468      0.878
#>  7  2016 VIC       6               70717            74780      0.946
#>  8  2016 VIC       7               69543            73391      0.948
#>  9  2016 VIC       8               69673            73373      0.950
#> 10  2016 VIC       9               69894            73627      0.949
#> # ... with 106 more rows
```
Accepts state and lga arguments for lga wise data but if the lga belongs to the state. 

```r

get_data_abs_age_education(state="WA",lga="Albany (C)",age=1:5)
#> # A tibble: 5 x 8
#>    year state lga          age population_educated total_population proportion
#>   <dbl> <chr> <chr>      <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 WA    Albany (C)     1                   0              348      0    
#> 2  2016 WA    Albany (C)     2                   0              413      0    
#> 3  2016 WA    Albany (C)     3                  44              434      0.101
#> 4  2016 WA    Albany (C)     4                 319              418      0.763
#> 5  2016 WA    Albany (C)     5                 355              376      0.944
#> # ... with 1 more variable: anomaly_flag <lgl>

# error message if the lga doesnt belong to the state 

get_data_abs_age_education(lga="York (S)",state="SA",age=1:5)
#> Error in `get_data_abs_age_education()`:
#> ! The LGA name provided does not belong to the state
#> i Specify the exact LGA name and the corresponding state it belongs to. See `abs_lga_lookup` for a list of all LGAs and the state it belongs to
#> x The lga name 'York (S)' does not belong to the state 'SA'
```

Accepts multiple states

```r

get_data_abs_age_education(state=c("QLD","TAS"),age=5)
#> # A tibble: 2 x 6
#>    year state   age population_educated total_population proportion
#>   <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 QLD       5               55416            61981      0.894
#> 2  2016 TAS       5                5745             6132      0.937

```
Accepts multiple lgas 

```r
get_data_abs_age_education(lga=c("Albury (C)","Barcoo (S)"),age=10)
#> # A tibble: 2 x 8
#>    year state lga          age population_educated total_population proportion
#>   <dbl> <chr> <chr>      <dbl>               <dbl>            <dbl>      <dbl>
#> 1  2016 NSW   Albury (C)    10                 615              654      0.940
#> 2  2016 QLD   Barcoo (S)    10                   7                7      1    
#> # ... with 1 more variable: anomaly_flag <lgl>

```
Accepts numeric vector for ages

```r
 
get_data_abs_age_work(state="NSW",age=10:20)

#> # A tibble: 11 x 6
#>     year state   age employed_population total_population proportion
#>    <dbl> <chr> <dbl>               <dbl>            <dbl>      <dbl>
#>  1  2016 NSW      10                   0            92149      0    
#>  2  2016 NSW      11                   0            89078      0    
#>  3  2016 NSW      12                   0            87806      0    
#>  4  2016 NSW      13                   0            87596      0    
#>  5  2016 NSW      14                   0            86382      0    
#>  6  2016 NSW      15               15654            88159      0.178
#>  7  2016 NSW      16               23972            89421      0.268
#>  8  2016 NSW      17               28962            89131      0.325
#>  9  2016 NSW      18               41965            89447      0.469
#> 10  2016 NSW      19               51514            92265      0.558
#> 11  2016 NSW      20               55800            94364      0.591

Created on 2022-05-30 by the reprex package (v2.0.1)

```

**Comment by aarathybabu97** [comment]
Update on `check_lga_name` :

`check_lga_name` with multiple lga errors without multiple_lga=TRUE argument.
```r
library(conmat)

check_lga_name(c("Albury (C)","Barcoo (S)"))
#> Error in `check_lga_name()`:
#> ! The LGA name provided matches multiple LGAs
#> i Specify the exact LGA name or set multiple_lga as `TRUE`. See `abs_lga_lookup` for a list of all LGAs
#> The lga name 'Albury (C)' matched multiple LGAs:
#> The lga name 'Barcoo (S)' matched multiple LGAs:
#> Albury (C)
#> Barcoo (S)

check_lga_name(c("Albury (C)","Barcoo (S)"),multiple_lga = TRUE)

Created on 2022-05-30 by the reprex package (v2.0.1)

```

**Review by njtierney — APPROVED** [review]

**Pull request merged**
